services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    depends_on:
#      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '15432:5432'
  temporal:
    image: 'davidsackett/temporal-dev:latest'
    ports:
      - '7233:7233'
      - '8233:8233'